Update Ci
Signed-off-by: Volodymyr Marchenko <volodymyr.marchenko@digitalasset.com>

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -15,13 +15,10 @@ on:
       - '**/*.md'
 
 jobs:
-
   build:
-
     runs-on: ubuntu-latest
 
     steps:
-
       - name: Checkout
         uses: actions/checkout@v4
 
@@ -52,7 +49,16 @@ jobs:
       - name: Test with Wokwi
         run: |
           set -e -o pipefail
-          pushd "${GITHUB_WORKSPACE}" 
+          printf "GITHUB_WORKSPACE=%s\n" "${GITHUB_WORKSPACE}"
+          printf "github.workspace=%s\n" "${{ github.workspace }}"
+          printf "PWD=%s\n" "${PWD}"
+          declare -a files=("wokwi-scenario.yaml" "diagram.json" ".pio/build/nano/firmware.elf")
+          for file in "${files[@]}"; do
+            if [ ! -f "$file" ]; then
+              echo "File $file not found"
+              exit 1
+            fi
+          done
           wokwi-cli --scenario=wokwi-scenario.yaml \
                     --diagram-file=diagram.json \
                     --elf=.pio/build/nano/firmware.elf \
@@ -60,6 +66,7 @@ jobs:
           popd
         env:
           WOKWI_CLI_TOKEN: ${{ secrets.WOKWI_CLI_TOKEN }}
+          
         shell: bash
         # uses: wokwi/wokwi-ci-action@v1
         # with:
